name: Terraform Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  terraform-fmt:
    name: Terraform Format Check
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Run terraform fmt
    - name: Check Terraform formatting
      run: terraform fmt -check -recursive

  terraform-plan:
    name: Terraform Init
    runs-on: ubuntu-latest
    needs: terraform-fmt

    steps:
    # Checkout the repository pq es otro step
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: code/terraform

    # Run Terraform Plan
    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan.out
      working-directory: code/terraform

    # Upload tfplan as artifact
    - name: Upload tfplan artifact
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: code/terraform/tfplan.out

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Download tfplan artifact
    - name: Download tfplan artifact
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: code/terraform

    - name: test
      run: |
        ls -l code/terraform 
        cat code/terraform/tfplan.out
        echo "Terraform plan file downloaded successfully."

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: code/terraform

    # Verify the plan
    - name: Verify Terraform plan
      run: terraform show -json tfplan.out
      working-directory: code/terraform

    # Apply Terraform changes
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan.out
      working-directory: code/terraform

