name: Welcome to the party (third) 
on:
  workflow_dispatch:
    inputs:
      thename:
        description: 'What is your name?' 
        required: true
jobs:
  say_hello:
    name: "Let's greet the user!" 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello there, ${{ inputs.thename }}!"